on:
  push:
    branches:
      - main
jobs:
  upload-artifact-every-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > hello_world.txt
      - name: "upload hello world artifact"
        uses: actions/upload-artifact@v4 # v4+ is recommended for compatibility with @actions/artifact v2
        with:
          path: hello_world.txt
          name: ${{ github.sha }}

  # This job will now correctly find the branch-push run even if triggered on a tag
  attempt-to-download-artifact-on-tagged-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Download from branch push
        uses: RequiemWorld/download-artifact@65566fc43f2a84c2fc171979f2ade13a767472d4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          artifact-name: ${{ github.sha }}

  get-feedback-for-non-existent-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt download of missing item
        uses: RequiemWorld/download-artifact@65566fc43f2a84c2fc171979f2ade13a767472d4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          artifact-name: "some-fake-name"