on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  upload-artifact-every-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > hello_world.txt
      - name: "upload hello world artifact"
        uses: actions/upload-artifact@v4 # v4+ is recommended for compatibility with @actions/artifact v2
        with:
          path: hello_world.txt
          name: ${{ github.sha }}

  # This job will now correctly find the branch-push run even if triggered on a tag
  attempt-to-download-artifact-on-tagged-commit:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Download from branch push
        uses: RequiemWorld/download-artifact@d4a63c6b8a8d1ec64642d4d1f9ea1b47402c3f1e
        with:
          path: "./download"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          artifact-name: ${{ github.sha }}

  get-feedback-for-non-existent-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt download of missing item
        uses: RequiemWorld/download-artifact@d4a63c6b8a8d1ec64642d4d1f9ea1b47402c3f1e
        with:
          path: ./download
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          artifact-name: "non-existent123455667"