on:
  push:
    branches:
      - main
jobs:
  upload-artifact-every-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo >> hello_world.txt
      - name: "upload hello world artifact"
        uses: actions/upload-artifact@v5
        with:
          path: hello_world.txt
          name: ${{ github.sha }}
  attempt-to-download-artifact-on-tagged-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: RequiemWorld/download-artifact@24
        with:
          path: ./directory_or_something
          name: ${{ github.sha }}

  get-feedback-for-non-existent-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: RequiemWorld/download-artifact@24
        with:
          path: ./directory_or_something
          name: ${{ github.sha }}